class Information {
  static final sex = ["Nam", "Nữ", "Gay", "Less"];

  static final listAge = [
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60"
  ];

  static final listProvince = [
    "Hà Nội",
    "TP HCM",
    "Đà Nẵng",
    "Cần Thơ",
    "Hải Phòng",
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cao Bằng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Tĩnh",
    "Hải Dương",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Phú Yên"
  ];
  static final listIncome = [
    "Chưa xác định",
    "Dưới 5 triệu",
    "Từ 5 - 8 triệu",
    "Từ 8 - 12 triệu",
    "Từ 12 - 18 triệu",
    "Từ 18 - 25 triệu",
    "Trên 25 triệu"
  ];
  static final listMarriage = ["Độc thân", "Ly hôn", "Ở góa"];
  static final listChildren = [
    "Chưa có",
    "Đã có (Sống cùng)",
    "Đã có (Không sống cùng"
  ];
  static final listHome = ["Thuê nhà", "Có nhà riêng", "Sống cùng bố mẹ"];
  static final listZodiac = [
    "Bạch dương",
    "Kim ngưu",
    "Song tử",
    "Cự giải",
    "Sư tử",
    "Xử nữ",
    "Thiên bình",
    "Bọ cạp",
    "Nhân mã",
    "Ma kết",
    "Bảo bình",
    "Song ngư"
  ];
  static final listTarget = ["Tìm người yêu", "Tìm bạn đời"];
  static final listStatus = [
    "Bình thương",
    "Nghiêm túc",
    "Rất ngiêm túc",
    "Cực kì nghiêm túc"
  ];
  static final listFormality = [
    "Kết bạn qua mạng xã hội",
    "Gọi điện, nhắn tin",
    "Hẹn gặp mặt",
    "Tất cả hình thức trên"
  ];
}
